### ISSUE TITLE
Map marker top left and corner

### ISSUE THREAD

**Issue by Norm2015** [petkivim/embed-google-map#1]
Site is Joomla 3.4.1 with Flexicontent and T3 Framework on local host. Plugin is placed within No Number slider and tabs and worked fine, however,  a recent change is the maps are not centering correctly i.e. the red marker is in the top left hand corner of the map.  When the page is refreshed  the marker and page correctly center but not on first load.

**Comment by petkivim** [comment]
Hi,

Thanks for contacting me. It's nice to hear that you're using my Embed Google Map plugin.

Is the map on a tab that's invisible (~not active) when the page loads? If yes, that's a known issue with Google Maps - only maps on visible (~active) tab get centered correctly.

Best regards,
Petteri

Date: Wed, 1 Apr 2015 23:50:10 -0700

**Comment by m3enkech** [comment]
Hi, 
I'd like to thank you for this plugin and looking a help with Long,Lat ... how can I change the default values?

**Comment by Norm2015** [comment]
Thanks Petteri

Yes, it is an invisible tab and I understand.

Norm

**Comment by petkivim** [comment]
There's a workaround that should fix the problem.

Place the {google_map}...{/google_map} tags inside a p element and add the below JavaScript to your site.

```
<p class="map"> {google_map}...{/google_map} </p>

$('.map', p).show(250, function() { var i = $(this).find('iframe'); var is = $(i).attr('src'); i.delay(250).attr('src', is); });
```

The script takes the ```src``` attribute of the I frame, then waits 250 milliseconds before setting the ```src``` again (to what it already is of course). This simple dom change triggers something in Google's code that causes the map to re-center itself.

**Comment by petkivim** [comment]
@m3enkech I created a new issue https://github.com/petkivim/embed-google-map/issues/2 for your question. The answer can be found there.
