### ISSUE TITLE
Infowindow hyperlink doesn't work

### ISSUE THREAD

**Issue by dantzu** [petkivim/embed-google-map#11]
Hi,
I'm trying to visualize a map where I have hyperlinks in the infowindows: 
<a href="http://www.filkab.solar">This is my hyperlink</a>
Unfortunately the code above doesn't work as it is supposed to and I can see the whole code when I click on a marker. Any suggestions? Thank you in advance.

**Comment by petkivim** [comment]
Hi,
I checked your site, but I didn't see any maps there. Could you provide the code that you've tried to use so I could take a look at it?

**Comment by dantzu** [comment]
Hi,
The site is still offline. You can login with the following credentials:
User: Guest
Pass: iamguest

The url of the page with the map is
http://filkab.solar/index.php/bg/projects

There are two maps. You will recognize your module on top of the other. I really like it but I need the links working. Thank you in advance.

**Comment by petkivim** [comment]
Hi,

Unfortunately this seems to be a feature of Google Maps Engine - it's not possible to use HTML code inside infowindow. If you take a look at the map in Google Maps Engine you can see that the problem exists there too.

https://www.google.com/maps/d/embed?mid=zj3qaUkKQZD8.k6xokwqGtfcs

Easy workaround for the problem would be to use the following text: ```My label: http://www.filkab.solar```. It doesn't look as nice as ```<a href="http://www.filkab.solar">My label</a>```, but it works.

Best regards,
Petteri

**Comment by dantzu** [comment]
Hi,
Thank you for your time.
The third map on the page uses another Google Maps module: System - Google Maps (http://extensions.joomla.org/extension/google-maps-by-reumer) .
The link works with this module which is strange?

**Comment by petkivim** [comment]
Hi,

The other plugin uses Google Maps JavaScript API that supports links in infowindow. My plugin is based on different approach that unfortunately does not support it.

Best regards,
Petteri

**Comment by dantzu** [comment]
I got it. Once again thank you for your time.
Very good plugin by the way, I think I'm still gonna use yours.
