### ISSUE TITLE
It doesn't work in contact "Miscellaneous Information"

### ISSUE THREAD

**Issue by vizo** [petkivim/embed-google-map#12]
It doesn't work in contact module under "Miscellaneous Information".

Or is there possibility to add it to contact template somewhere?

**Comment by munnibhai** [comment]
It doesnt work for me either. have tried many different ways and I think misc. info portion filters all tags except the basic ones

**Comment by petkivim** [comment]
Unfortunately the contact module doesn't support content plugins. ```content.prepare``` event does not get fired when Miscellaneous Information field is rendered.
