### ISSUE TITLE
Map Showing Competing Businesses

### ISSUE THREAD

**Issue by HarryO22** [petkivim/embed-google-map#13]
Great product.  I added it to my developmental website and it looks good. My only issue is that when I add the business name and location, the map shows competing businesses:

{google_map}Meissa Hair Braiding 11763 Central Avenue Waldorf MD 20601{/google_map}

![meissa with other businesses](https://cloud.githubusercontent.com/assets/15200044/10585308/a814e528-7664-11e5-9c6a-614d042f3472.JPG)

When I just use the address, it does not show competing businesses:

{google_map}11763 Central Avenue Waldorf MD 20601{/google_map}

![without businesses](https://cloud.githubusercontent.com/assets/15200044/10585429/29ce8a06-7665-11e5-8950-d71f188cbbf0.JPG)

I want to add the business name without showing the other businesses, is that possible?

Cordially,

HarryO22

**Comment by petkivim** [comment]
Hi,

Unfortunately the Google Maps API that my plugin is using does not support custom labels. Otherwise you could have used the address and then add the name of your business to the label. Therefore I'm afraid it's not possible to add the business name without showing the other businesses.

Best regards,
Petteri

**Comment by HarryO22** [comment]
Thank you for your prompt assistance.

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Wed, Oct 21, 2015 at 7:56 AM -0700, "Petteri Kivimäki" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Unfortunately the Google Maps API that my plugin is using does not support custom labels. Otherwise you could have used the address and then add the name of your business to the label. Therefore I'm afraid it's not possible to add the business name without showing the other businesses.

Best regards,
Petteri

-
