### ISSUE TITLE
Wrong location displayed

### ISSUE THREAD

**Issue by gcarne** [petkivim/embed-google-map#14]
Hi, 
Just installed your Embed Google Map in one of my modules. For the time being my website is on Localhost/XAMPP. The map is showing my current location (or the location of my personal Google Account), not the address in {google_map}address-to-be-displayed{/google_map}. Can you tell me why?
Thanks,
GC

**Comment by petkivim** [comment]
Hi,

Could you please send me the following information:

* the exact code that you used for embedding the map, e.g. ```{google_map}96 Euston Rd, London{/google_map}```
* HTML code that gets generated when you load the page

Best regards,
Petteri

**Comment by gcarne** [comment]
Hello Petteri,

 

Thank you for replying. I wanted to solve my problem and installed another extension for Google Maps which worked. 

 

Best regards,

Gunnar

 

Logo 600

 

Sleep in Silk Germany

Inh. Gunnar Carne

Taunusstraße 8

64521 Groß-Gerau

 

Tel: 06152 - 669 46 45

 

Mail: info@sleepinsilk.de

 

www.sleepinsilk.de

 

Von: Petteri Kivimäki [mailto:notifications@github.com] 
Gesendet: Samstag, 24. Oktober 2015 09:18
An: petkivim/embed-google-map
Cc: gcarne
Betreff: Re: [embed-google-map] Wrong location displayed (#14)

 

Hi,

Could you please send me the following information:

*	the exact code that you used for embedding the map, e.g. {google_map}96 Euston Rd, London{/google_map} 
*	HTML code that gets generated when you load the page

Best regards,
Petteri
