### ISSUE TITLE
My Google Map disappears

### ISSUE THREAD

**Issue by resomanager** [petkivim/embed-google-map#15]
Hello,

My Map was displaying correctly for a long time, and now it loads for a split second and disappears...

On this website : http://hotel-marine.fr/acces-hotel-restaurant-saint-herblain.html

Do you have any idea about a fix ?

**Comment by petkivim** [comment]
Hi,

Looks like google changed something on their side if you didn't make any changes on your site. I checked the link and at the moment the map is working. Were you able to fix the problem or did you change to another plugin?

**Comment by resomanager** [comment]
Hi,

It seems like the problem fixed itself without doing anything. Thanks anyways.

Kevin Schultz,
Community Manager
RESO

Le 30 déc. 2015 à 19:42, Petteri Kivimäki <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi,

Looks like google changed something on their side if you didn't make any changes on your site. I checked the link and at the moment the map is working. Were you able to fix the problem or did you change to another plugin?

**Comment by petkivim** [comment]
Hi,

Good to hear that the problem was solved. Maybe it was just a temporary problem on Google's service.

Best regards,
Petteri
