### ISSUE TITLE
Map does not accept the desired address

### ISSUE THREAD

**Issue by hubstone** [petkivim/embed-google-map#16]
Have successfully used your amazing map plugin many times, but when I try addresses on Calder Avenue Beaumont TX a map of the word is displayed with no 'google marker' showing location. 
Ref: Code = {google_map} The Brew Shop  2400 Calder Ave, Beaumont, TX 77702|width:300|height:300|link:yes|link_label:Label{/google_map}

 This business also has a Lake Charles Louisiana address that displays properly.
Ref: Code = {google_map} The Brew Shop  2917 Common Street  Lake Charles, LA 70601|width:300|height:300|link:yes|link_label:Label{/google_map}

**Comment by petkivim** [comment]
Which version of Google Maps you're using: new, classic or embed? With embed it behaves just like you described, but with new the map displays correctly. I used the below code:

```
{google_map}The Brew Shop 2400 Calder Ave, Beaumont, TX 77702|width:300|height:300|link:yes|link_label:Label|version:new{/google_map}
```

**Comment by hubstone** [comment]
I was using 'classic'. I will now switch to 'embed'.  Thanks for the reply.
 

    On Wednesday, February 17, 2016 10:16 AM, Petteri Kivimäki <notifications@github.com> wrote:
 

 Which version of Google Maps you're using: new, classic or embed? With embed it behaves just like you described, but with new the map displays correctly. I used the below code:{google_map}The Brew Shop 2400 Calder Ave, Beaumont, TX 77702|width:300|height:300|link:yes|link_label:Label|version:new{/google_map}
