### ISSUE TITLE
Syntax showing as well as maps

### ISSUE THREAD

**Issue by mollymilne** [petkivim/embed-google-map#17]
Hi,
If you look at my page here: http://hkjfl.com/new/index.php/venues
You can see that the maps show beautifully when you scroll down, but the syntax is also showing - in what looks like another complete version of the table...
Any idea why this might be happening?

**Comment by petkivim** [comment]
Hi,

It's really strange that the syntax is also visible, it definitely shouldn't be. The html code shows that the syntax is placed inside ```article-intro``` section. Could you check your article settings and make sure that you haven't added an intro section to the article. More information about the intro section can be found [here](https://docs.joomla.org/Splitting_an_Article_into_an_introduction_with_a_link_to_read_more).
