### ISSUE TITLE
how do you disable the mouse scroll on ipad and iphones again...

### ISSUE THREAD

**Issue by nielsgeurs** [petkivim/embed-google-map#18]
i've read about it before on your 'old' site.. but can't find it anymore.. thanks!
Niels

**Comment by petkivim** [comment]
It's possible to disable scroll on the map. This can be implemented using CSS and jQuery. Please see a simple example below.

Wrap the  ```{google_map} ``` tags with a class (.maps in this example). Change the CSS of the iframe to  ```pointer-events: none ``` and then using jQuery's click function to the parent element you can change the iframe's CSS to  ```pointer-events:auto ```.

Embedding the map:
 ```
<div class='maps'>
    {google_map}address{/google_map}
</div>
 ```
CSS:
 ```
.maps iframe{
    pointer-events: none;
}
 ```
jQuery:
 ```
$('.maps').click(function () {
    $('.maps iframe').css("pointer-events", "auto");
});

$( ".maps" ).mouseleave(function() {
  $('.maps iframe').css("pointer-events", "none");
});
 ```
Best regards,
Petteri
