### ISSUE TITLE
part of syntax is showing.  The map is working perfect but I need to be able to delete the syntax from showing.

### ISSUE THREAD

**Issue by target4fun** [petkivim/embed-google-map#19]
part of syntax is showing.  The map is working perfect but I need to be able to delete the syntax from showing.

http://arma15.com/dealers

**Comment by petkivim** [comment]
The line below is somehow ended up in a wrong place of the article's HTML code. You should try to edit the article in HTML view and just simply remove the line below from the code. That should fix the issue.

```
https://www.google.com/maps/d/embed?mid=z7WP5-ZhMODE.kFj6fT1YGMn0{/google_map}}
```

Br,
Petteri

**Comment by target4fun** [comment]
Ive looked at it several times and it only shows 1 line of code I cant find where the extra line of syntax could be showing up that is posting.  See screen shot 

    On Thursday, March 24, 2016 10:40 AM, Petteri Kivimäki <notifications@github.com> wrote:
 

 The line below is somehow ended up in a wrong place of the article's HTML code. You should try to edit the article in HTML view and just simply remove the line below from the code. That should fix the issue.https://www.google.com/maps/d/embed?mid=z7WP5-ZhMODE.kFj6fT1YGMn0{/google_map}}
Br,
Petteri—

**Comment by petkivim** [comment]
Unfortunately the screenshot is missing from your comment. Did you check the HTML code of the page like in the image below? If you have copied the tags ```{google_map}...{/google_map}``` from a website, it's possible  that there's some unwanted HTML code that's causing the problem.

![img](https://cloud.githubusercontent.com/assets/575897/14063776/209e42c6-f3e9-11e5-834d-c870c4185f37.png)

**Comment by target4fun** [comment]
Yes sir, that is exactly how mine looks its one line of html code I used that button and also brought up html code from the article.  I saw no way to upload a the shot so i did so with dropbox link
arma15dealers.jpg

  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
arma15dealers.jpg
 Shared with Dropbox  |   |

  |

  |

 

    On Saturday, March 26, 2016 11:00 PM, Petteri Kivimäki <notifications@github.com> wrote:
 

 Unfortunately the screenshot is missing from your comment. Did you check the HTML code of the page like in the image below? If you have copied the tags {google_map}...{/google_map} from a website, it's possible that there's some unwanted HTML code that's causing the problem.—

**Comment by petkivim** [comment]
Unfortunately the link got filtered from your post. You can attach files to the comments by dragging & dropping them on the bottom of the comment field or clicking "selecting them" link.

**Comment by target4fun** [comment]
[https://dl.dropboxusercontent.com/u/46283469/Screenshot%202016-04-07%2015.58.13.png](url)

**Comment by petkivim** [comment]
Thanks. Based on the screenshot everything seems to be OK on the article. The syntax is showing on the part that is for SociaI Buttons plugin. Is that a different module or how the buttons are added? I installed Social Buttons on my test site, but I wasn't able to repeat the issue. However, I noticed that on my test site the buttons were added inside ```articleBody``` section, but on your site they're inside another section before ```articleBody```. At this point I'd say that the problem is somehow related to Social Buttons plugin. Could you try to disable it and see what happens?
