### ISSUE TITLE
PHP 7 deprecated constructor

### ISSUE THREAD

**Issue by krogias** [petkivim/embed-google-map#20]
In Joomla! 3.5 with php7 there's an error: 

> Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgContentembed_google_map has a deprecated constructor in C:...\plugins\content\embed_google_map\embed_google_map.php on line 21

**Comment by petkivim** [comment]
Fixed in version [2.0.2](https://github.com/petkivim/embed-google-map/releases/tag/v2.0.2).
