### ISSUE TITLE
support for modules

### ISSUE THREAD

**Issue by jumpingfella** [petkivim/embed-google-map#21]
Hi, is it possible to have this working in joomla modules too?

**Comment by petkivim** [comment]
Embed Google Map is a content plugin and it is for use specifically within a Joomla article, which is managed by the com_content component. By default, a content plugin will not run in other components as it's originally designed to run within com_content only. However, Custom HTML module is also supported, but you must set ```Prepare Content``` setting to ```Yes``` on module's options. 

If you want to run a content plugin within other components, you may achieve this by adding a trigger in your component.

**Comment by jumpingfella** [comment]
ok, thx!
