### ISSUE TITLE
scroll on the map

### ISSUE THREAD

**Issue by MartinaUs** [petkivim/embed-google-map#23]
Hi! 
I have read Your posts about switching off mousescrolling on embeded map... but I still can't make it on my website. I did everything  You advised,  but can't fix my problem. 

So! When I added class .maps with css ".maps iframe{pointer-events: none;}" my map became static. Then I added the code from Your's post to themeplate but my map stay static.... Help me, please, to find my mistakes... I, m a user... not a dev..

There are examples of my attempts to add JS between <head></head>)))
First was:
`"<script type="text/javascript">
$('.maps').click(function () {
   $('.maps iframe').css("pointer-events", "auto");
});

$( ".maps" ).mouseleave(function() {
 $('.maps iframe').css("pointer-events", "none");
});
</script>"`

Second ))):
"<script type="text/javascript" src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template;?>/js/jquery-1.12.0.min.js" />
    <script type="text/javascript">
$('.maps').click(function () {
   $('.maps iframe').css("pointer-events", "auto");
});

$( ".maps" ).mouseleave(function() {
 $('.maps iframe').css("pointer-events", "none");
});
</script>"
And the last )
<script type="text/javascript" src="<?php echo $this->baseurl ?>/templates/<?php echo $this->template;?>/js/jquery-1.12.0.min.js">jQuery.noConflict();</script>
    <script type="text/javascript">
jQuery('.maps').click(function () {
  jQuery('.maps iframe').css("pointer-events", "auto");
});

jQuery( ".maps" ).mouseleave(function() {
jQuery('.maps iframe').css("pointer-events", "none");
});
</script>

**Comment by petkivim** [comment]
Hi,

You're referring to issue #18. It seems that you've modified the CSS file correctly, and now you should only add few lines of jQuery. Adding the below lines to your template should do the trick. Remember to refresh the page (``` CTRL + F5```) after updating the template.

 ```
<script type="text/javascript">
    jQuery(document).ready(function($){
        $('.maps').click(function () {
            $('.maps iframe').css("pointer-events", "auto");
        });

        $( ".maps" ).mouseleave(function() {
            $('.maps iframe').css("pointer-events", "none");
        });
    });
</script>
 ```
Best regards,
Petteri

**Comment by MartinaUs** [comment]
Oh! That's awesome! It works!
Thank You, Petteri, soooo much!))))))))
