### ISSUE TITLE
loading {google_map} after the entire page has loaded? currently adding some 4 sec to the whole page loading time

### ISSUE THREAD

**Issue by olivdee** [petkivim/embed-google-map#24]
hi and thanks for the great plugin!
we are in the process of optimizing a website using it, and the problem is that because it takes ages to load all gmap ressources (4 sec) the preloader/spinner on the website is still not showing content. our preloader/spinner fades out and reveales the content after "load" event. is it somehow possible to load all content by {google_map} after the "load" event = after the entire page has loaded?
any info/help/idea appreciated!

**Comment by petkivim** [comment]
Hi,

You could try the script below and see if it helps. It removes the value of ```src``` attribute from all the ```iframe```s on ```ready``` event which prevents them loading. The values are restored on ```load``` event with 2 seconds delay.

```
(function ($)
{
    // Array for frame sources
    var sources = [];

    $(document).ready(function ()
    {
        // Loop through all the iframes on the page
        $("iframe").each(function () {
            // Get the value of src
            var src = $(this).attr('src');
            // Set src=""
            $(this).attr('src', '');
            // Store src in the array
            sources.push(src);
        });
    });

    $(window).load(function () {

        function loadGMaps() {
            var i = 0;
            // Loop through all the iframes on the page
            $("iframe").each(function () {
                // Get src value from the array
                $(this).attr('src', sources[i]);
                i++;
            });
        }
        // Set 2 seconds delay for loading Google Maps
        setTimeout(loadGMaps, 2000);
    });
})(jQuery);
```

**Comment by olivdee** [comment]
great idea/solution. works like a charm! thanks so much

**Comment by petkivim** [comment]
You're welcome. That's great to hear. :)
