### ISSUE TITLE
Change map overlay label text

### ISSUE THREAD

**Issue by pucaraSB** [petkivim/embed-google-map#27]
Hi,
I used the Classic Map version along with coordinates (my location is a country property). 
Is it possible to change the listed coordinates in the map overlay label to read something other than the latitude and longitude?

You can see what I mean on my website: pucaraspanishschool.ec (the map is in the footer)

Or if it is not possible to change that text, how can I remove that label? I have "Show Info" selected to "No" in the backend.

Thank you in advance for your help!

**Comment by petkivim** [comment]
Hi,

Unfortunately Google does not support the Classic version anymore and all the URLs pointing the Classic version are automatically redirected to the current version which does not provide the possibility to hide or customize the map label. For this reason ```Show Info``` and ```Info Label``` properties do not have any effect anymore and therefore they should be removed.

My plugin is based on embedding the map using ```iframe``` without Google Maps JavaScript API. The JavaScript API supports changing the label content, but it requires getting an API key. There are other plugins available that based on the JavaScript API so you may want to try one of those if hiding the label or updating the label text is a must have requirement for you.

Br,
Petteri

**Comment by pucaraSB** [comment]
Ok, I understand. Thanks so much for your speedy reply. I will stick with things the way they are. I really appreciate the simplicity of this extension. :)
