### ISSUE TITLE
Is it possible to make the map responsive?

### ISSUE THREAD

**Issue by pucaraSB** [petkivim/embed-google-map#28]
One more question– Is it possible to make the map responsive? I have it placed inside a module, however it's width is not changing with the screen size. Thanks!

**Comment by petkivim** [comment]
Just use the percent sign ```%``` when you define the width and the map should be responsive.

```
{google_map}Address|width:100%|height:300{/google_map}
```

**Comment by pucaraSB** [comment]
Perfect! Thank you so very much!

**Comment by petkivim** [comment]
You're welcome. :)
