### ISSUE TITLE
Having trouble installing into Joomla

### ISSUE THREAD

**Issue by paintedbrain** [petkivim/embed-google-map#29]
Hi I am having trouble installing into Joomla, can I please get some help?

I am getting Error Archive does not exist.

Warning
JFolder::create: Could not create directory Path: /home/dhthemec

Warning: Failed to move file!

JFolder: :files: Path is not a folder. Path: /home/dhthemec/public_html/tmp/install_579ad8b307af1

JFolder: :folder: Path is not a folder. Path: /home/dhthemec/public_html/tmp/install_579ad8b307af1

JFolder: :files: Path is not a folder. Path: /home/dhthemec/public_html/tmp/install_579ad8b307af1

JInstaller: :Install: Cannot find Joomla XML setup file

**Comment by petkivim** [comment]
Hi,

I'm sorry for the slow response...I've been traveling and got back home yesterday.

Could you give me some more information about your system: Joomla version, OS version, PHP version?

Did you download the installation package using the URL below? How did you try to install the plugin (download & upload using Joomla UI, download & upload using sftp, Joomla web installer)?

https://github.com/petkivim/embed-google-map/releases/download/v2.1.0/plg_content_embed_google_map-2.1.0.zip

**Comment by paintedbrain** [comment]
Hi thank you very much for getting back to me.

 Joomla! 3.2.7,
<http://www.manawatusf.org.nz/administrator/index.php?option=com_joomlaupdate>
Not
sure about the php sorry, where can I find that infor for you?

I'm running windows 10.

Best regards,
Sean

**Comment by petkivim** [comment]
On a Linux system PHP version can be checked with ```$ php --version``` command.

One way to check the version is to create a phpinfo file, open a plain text file, add the following lines, and save:

Filename: phpinfo.php

```
<?php
phpinfo();
?>
```

Then access phpinfo.php page and you should see PHP version and many other information related to PHP settings.

Have you tried to install any other plugins and did you have any problems with them?

**Comment by paintedbrain** [comment]
Yes I did try another install and got the same problem, I will try to
access the hosts C Pannel to find out the php version.

**Comment by paintedbrain** [comment]
[image: Inline image 1]
Hopefully this shows the php version?

**Comment by paintedbrain** [comment]
There was this method I used a few years ago where I went into Joomla admin
and disabled some things that allowed me to use google maps in an article
but I can't find the instructions.

**Comment by petkivim** [comment]
Unfortunately I can't see the image that you tried to post earlier. However, I think that the problem is related to the permissions of the web server's directory as you have the same problem with other plugins as well. The first row of the error message is probably the root cause and the other operations fail because of that.

```
Warning JFolder::create: Could not create directory Path: /home/dhthemec
```

I've seen a similar error message when I've tried to install a plugin in a hardened version of Joomla (web server didn't have write permissions to public_html folder). Could you check that the web server has sufficient permissions to write to the directory where Joomla is located?

**Comment by paintedbrain** [comment]
Ok sure I will check with the host today. PHP was 5.5 native

**Comment by paintedbrain** [comment]
Do you know what permissions are needed?

**Comment by petkivim** [comment]
The web server needs read, write and execute permissions on the directory where Joomla is located.

**Comment by paintedbrain** [comment]
Ok, I have the plugin installed and I have enabled it.

I can't seem to get the embed working. Does this look right?
*latitude,longitude = 40°21'22.5"S 175°36'21.7"E

**Comment by petkivim** [comment]
The coordinates must be in decimal degree format, e.g. ```{google_map}60.1705,24.9384{/google_map}```.

**Comment by paintedbrain** [comment]
How do you get that from Google maps?

**Comment by petkivim** [comment]
You can convert the coordinates using this tool: http://www.gps-coordinates.net/gps-coordinates-converter.

**Comment by petkivim** [comment]
The correct code for embedding the map is ```{google_map}-40.35625, 175.60602{/google_map}```
