### ISSUE TITLE
Multiple locations

### ISSUE THREAD

**Issue by Dakota09** [petkivim/embed-google-map#3]
Hi love the plugin, but was wondering if one map can support multiple listings?  Is so what would the code look like?  Thanks!

**Comment by petkivim** [comment]
Hi @Dakota09,

Thanks for contacting me. It's nice to hear that you're using my Embed Google Maps plugin.

If you want to embed a map with multiple locations, first you need to create a map in Google Maps and store it under My places.

After creating the map you can embed it in Joomla using my plugin. You should copy the URL from the Embed map screen of Google Maps. Please see the link below.

https://support.google.com/maps/answer/3544418?hl=en

You need to copy the URL from iframe src and place it inside {google_map} tags in Joomla. 

{google_map}https://maps.google.com/maps/....{/google_map}

**Comment by Dakota09** [comment]
Thank you for the prompt reply and assistance!  That was as I suspected, bt wanted to confirm first!  Thanks again!!!
 

-------- Original Message --------Subject: Re: [embed-google-map] Multiple locations (#3)From: Petteri Kivimäki <notifications@github.com>Date: Fri, May 22, 2015 7:38 amTo: petkivim/embed-google-map <embed-google-map@noreply.github.com>Cc: Dakota09 <tony@dakotawebcreations.com>
Hi @Dakota09,
Thanks for contacting me. It's nice to hear that you're using my Embed Google Maps plugin.
If you want to embed a map with multiple locations, first you need to create a map in Google Maps and store it under My places.
After creating the map you can embed it in Joomla using my plugin. You should copy the URL from the Embed map screen of Google Maps. Please see the link below.
https://support.google.com/maps/answer/3544418?hl=en
You need to copy the URL from iframe src and place it inside {google_map} tags in Joomla. 
{google_map}https://maps.google.com/maps/....{/google_map}
