### ISSUE TITLE
Ongelma Plugarin käytössä

### ISSUE THREAD

**Issue by ElegantPaw** [petkivim/embed-google-map#30]
Hei

Olen käyttänyt kyseistä plugaria onnistuneesti monilla sivuilla. Eli kiitos tästä ja toivottavasti ensimmäiseen ongelmaankin saan nyt vastauksen.  Nyt ongelmaksi muodostui erään Helsinkiläisen ravintolan google mapsin osoite. Ei suostu mitenkään päin sitä sinne ottamaan. Onko sinulla vinkkejä tähän. Kokeilin kyseiselle sivustolle, että esimerkiksi oma google mapsin linkki toimii moitteettomasti. Eli voiko tämä ongelma johtua erikoismerkeistä liikkeen google mapsin nimessä?

**Comment by ElegantPaw** [comment]
Kyseessä tämän paikan osoite https://goo.gl/maps/E5muvTYqxym

**Comment by petkivim** [comment]
Hei,

Luulisin, että ongelma liittyy juuri liikkeen nimessä oleviin erikoismerkkeihin. Voisitko lähettää minulle sivun osoitteen, jolle kyseinen kartta on upotettu, niin voisin tutkia ongelmaa tarkemmin? Palaan huomenna kotiin lomamatkalta, joten pääsen tutkimaan asiaa tarkemmin keskiviikkona tai torstaina.

**Comment by ElegantPaw** [comment]
Hei
Kiitos pikaisesta vastauksestasi reissun päältä. Yritän tässä myös selvittää pääsenkö käsiksi näihin googlen my business tileihin niin voisin niitä erikoismerkkejä muuttaa. Mutta jos näin ei käy niin sivuston väliaikainen osoite on. http://milis.kennelnds.com  Laitan sivuston keskiviikkona aamupäivästä auki. Ilmoitan jos saan muutettua tilien osoitteet ja näin homman toimimaan.

**Comment by petkivim** [comment]
Hei,

Lomat on nyt vietetty ja pääsin kokeilemaan hvaitsemasi ongelman toistamista. Sain lisättyä haluamasi paikan kartalle käyttämällä alla olevaa koodia.

```
{google_map}MILI`S FOOD CAFÉ LEPPÄVAARA{/google_map}
```

Ainakin ```&```-merkki aiheuttaa ongelmia kartan kohdistuksen kanssa. Lisäksi ```MILI`S```-sanan kohdalla kohdalla heittomerkin (```'```) tai akuuttiaksentin (```´```) käyttö ``` ` ```-merkin sijasta aiheuttaa sen, että oikeaa paikkaa ei löydy.

**Comment by ElegantPaw** [comment]
Näköjään se ei halua oikein toimia tuollakaan koodilla. Meitä on neljä jo testannut ja lukee vaan Henttaa. Eikä se löydä kyseistä paikkaa.

**Comment by petkivim** [comment]
Minulla kartta näkyy nyt ihan oikein aiemmin lähettämäsi linkin takaa löytyvällä sivustolla:

http://milis.kennelnds.com/yhteystiedot-ja-aukioloajat/espoonlahti

![img](https://cloud.githubusercontent.com/assets/575897/17367549/12970ad0-5999-11e6-8605-087d3f25dd79.png)

**Comment by ElegantPaw** [comment]
Heippa
Mielenkiinnosta kysyn, millä selaimella sitä katselet kun minulla ja kaikilla muilla minun tutuilla näkyy edelleen vaan jossain Henttaan kohdalla oleva vaikka on katseltu selaimilla jolla ei ole koskaan avattukaan tätä sivustoa?

**Comment by petkivim** [comment]
Mielenkiintoista...itselläni on Windows 10 ja Firefox 47.0.1. Myös MS Edgellä sivu näkyy oikein. Oletteko kokeilleet sivun uudelleen lataamista ```CTRL``` + ```F5``` koodin muuttamisen jälkeen?

**Comment by ElegantPaw** [comment]
Itse testasin uusimmalla Safarilla, Chromella, Firefoxilla ja Edgellä. Enkä saanut toimimaan.  Eikä kaverikaan saanut näillä selaimilla näkymään kuin Henttaan. Kaikilla sentään näkyy kartasta sama kohta. Toinen kaveri katsoi kanssa. Hän sai vaan Firefoxilla sen sentään näkymään, mutta ei muilla selaimilla. Mielenkiintoinen ongelma jo tosiaan.

**Comment by petkivim** [comment]
Voisitko ottaa vaikka Firefoxilla copy/pasten pluginin generoimasta html-koodista? Itselläni koodi näyttää tältä:

```
<iframe class="embedGoogleMap" style="border: 0px solid #000000" src="http://maps.google.com/?q=mili%27s+food%26amp%3Bcaf%C3%A9+espoonlahti&amp;z=14&amp;t=m&amp;hl=fi&amp;output=svembed" height="400" width="300"></iframe>
```

Lisäksi pluginin asetuksista voisi kokeilla laittaa ```Load asynchronously``` -asetuksen arvoksi ```Yes``` ja ```Delay```-asetuksen arvoksi vaikka ```500``` ms. Muutoksen myötä kartta ladataan vasta, kun koko muu sivu on ensin latautunut.

**Comment by ElegantPaw** [comment]
<iframe class="embedGoogleMap" style="border: 0px solid #000000" src="http://maps.google.com/?q=mili%27s+food+caf%C3%A9+espoonlahti&amp;z=14&amp;t=m&amp;hl=fi&amp;output=svembed" height="400" width="300"></iframe>

Tälläinen on koodi minulla päin kun otan sen Firefoxilla. Eikä edelleen kartat toimi. Laitoin ne latautumaan myöhemmin.

**Comment by ElegantPaw** [comment]
`<iframe class="embedGoogleMap" style="border: 0px solid #000000" src="http://maps.google.com/?q=mili%27s+food+caf%C3%A9+espoonlahti&amp;z=14&amp;t=m&amp;hl=fi&amp;output=svembed" height="400" width="300"></iframe>`

**Comment by ElegantPaw** [comment]
Ostin maksullisen moduulin asiaan ja sain tämän toimimaan eli ei tarvitse enää asiaa pohtia :) Kiitän avusta tähän asti vaikka toimivuutta ei saatukaan aikaiseksi.

**Comment by petkivim** [comment]
Ok, kiitos tiedosta! Harmi juttu, että ei saatu ongelmaa tämän plugarin osalta ratkaistua, mutta pääasia tietenkin, että itse ongelma ratkesi. :)
