### ISSUE TITLE
Map not showing in frontend

### ISSUE THREAD

**Issue by mwprojas** [petkivim/embed-google-map#31]
Hello,
I installed the plugin successfully and enabled it.  When I enter the code in my article, the map doesn't display on the front end.  Instead, the code I typed shows up.

{google_map}0.4454673,33.1796483{google_map}

Here's a link to the page: [http://pearlschildrensfund.org/index.php/about-us](url)

Thanks!

**Comment by petkivim** [comment]
Hi,

There's a slash ```/``` character missing from the closing tag ```{google_map}``` => ```{/google_map}```:

```
{google_map}0.4454673,33.1796483{/google_map}
```

Br,
Petteri
