### ISSUE TITLE
Problem with iwt cookie alarm

### ISSUE THREAD

**Issue by parsifaltheking** [petkivim/embed-google-map#32]
Hi, i've installed you plugin and it works.
With cookie law i've installed a plugin iwt cookie alarm that after a user accept, enable cookies and enable access to your plugin, but it not works.
The developer of plugin inform me to write you for the problem. 
The problem is in this page:  http://www.meggcasalinghi.it/web/index.php/dove-siamo

If click on accept cookie, the page are reload but the maps not load.. is your plugin developed in jquery?

I've activate jquery no conflicts but not works.

**Comment by petkivim** [comment]
Ciao,

Per caso sei italiano? Hai attivato il mio plugin dopo averlo installato? Viene fuori il codice invece della mappa se il plugin non è stato attivato. Il plugin non usa jQuery o cookies quindi quello non dovrebbe causare il problema.

Petteri

**Comment by parsifaltheking** [comment]
Sì sono italiano.
Allora ho installato il tuo plugin e poi iwt cookie alarm che mi richiede
di dare al plugin che voglio bloccare il gruppo degli utenti che hanno
accettato i cookie.
Ora la prima volta viene fuori il codice ed e' corretto ma quando accetto
il sistema dovrebbe sbloccare il gruppo e mettermi nel gruppo utenti
sbloccati in modo da attivare il tuo plugin.. ma questo non succede.. e non
riesco a capire il perché..

Se gli do come livello di accesso al plugin public funziona senza problemi..

Quindi non so capire da dove arriva il problema

Andrea

Il 12/Ott/2016 07:39 PM, "Petteri Kivimäki" <notifications@github.com> ha
scritto:

**Comment by petkivim** [comment]
Purtroppo non conosco iwt cookie alarm perchè non l'ho mai usato. Comunque vedere il codice sul sito vuol dire che il mio plugin non viene eseguito per qualche motivo. Hai controllato se ci sono errori sul log? Potresti provare a cambiare l'ordine di esecuzione dei plugins e spostare Embed Google Map prima di iwt cookie alarm. [Qui](https://www.regularlabs.com/blog/242-plugin-order-is-important) ci sono le istruzioni in inglese.
