### ISSUE TITLE
Zoom not working

### ISSUE THREAD

**Issue by Vulgum-Techus** [petkivim/embed-google-map#33]
Did install the plugin in replacement of the Reumer's one which I remove for good.

The problem I'm facing is Zoom. Applying a value in defauts parameters has no effect -> remains at 14 and putting |zoom:N in the command line stops the map from showing up in the page.

I changed the plugin order to no avail. What should I do next?

**Comment by petkivim** [comment]
Could you send me a link to your site or post here the html code that the plugin generates? Without seeing the code it's difficult to say what causes the problem.

**Comment by Vulgum-Techus** [comment]
Thanks!
Here is the link to it... http://vt.cx/aX

**Comment by petkivim** [comment]
Thanks! Have you copied the address from a webpage? It seems that there's some HTML formatting information that should not be there. This is the code that is generated:

```
<iframe class="embedGoogleMap" style="border: 0px none rgb(0, 0, 0); pointer-events: none;" src="https://www.google.com/maps?q=%3Cspan+style%3D%22font-size%3A+13.3333px%3B%22%3E29+rue+des+Orteaux+-+75020+Paris%3Cspan+style%3D%22font-size%3A+12.16px%3B%22%3E&amp;z=3&amp;t=m&amp;hl=fr&amp;output=embed" width="460" height="400"></iframe>
```

This is how should look like:

```
<iframe class="embedGoogleMap" style="border: 0px none rgb(0, 0, 0); pointer-events: none;" src="https://www.google.com/maps?q=29+rue+des+Orteaux+-+75020+Paris&amp;z=3&amp;t=m&amp;hl=fr&amp;output=embed" width="460" height="400"></iframe>
```

To get rid of all the HTML formatting information you must copy/paste the address to notepad first, and then copy the code from notepad to Joomla article. After that the code should work as expected.

```
{google_map}9 rue des Orteaux - 75020 Paris|zoom:3{/google_map}
```

**Comment by Vulgum-Techus** [comment]
Well done Peter! It works like a charm. I usually copy with [[ctrl]] to avoir this but this time, I just typed it in and kept the doc span in the process. How dumb. Should have thought of that right away. Sorry for the noise and thanks for the amazingly short time of response!!!!

**Comment by petkivim** [comment]
Happy to hear that the problem was resolved. :)
