### ISSUE TITLE
Is it possible to make the map 'non-panable' and remove the zoom and pin?

### ISSUE THREAD

**Issue by fribse** [petkivim/embed-google-map#34]
Hi there

I've been using Reumertech's google map for a while, but it looks like the project is now dead.
He had a setting to make the map 'non panable', remove the zoom, and remove the pin, which I would love to have back.

Best regards
Kenneth

**Comment by petkivim** [comment]
Hi Kenneth,

So basically you would like to have the map pretty much static if I understand correctly. Unfortunately my plugin does not support this kind of behavior currently.

Br,
Petteri
