### ISSUE TITLE
Google Issues?

### ISSUE THREAD

**Issue by webwizardworks** [petkivim/embed-google-map#35]
I've been using this wonderful plugin on several pages for one of my clients. Current the pages have to be refreshed several times before the pdf appears. Do we know if Google Docs Viewer is having issues?

**Comment by petkivim** [comment]
Thanks, nice to hear that you've found my plugin useful. I was able to replicate your problem with Firefox on my own test site, but with Chrome the everything works normally. Based on this it seems that Google Docs Viewer is having some issues or they have changed something in the service.  

Br,
Petteri
