### ISSUE TITLE
Routeplanner

### ISSUE THREAD

**Issue by edwerf** [petkivim/embed-google-map#36]
Is it possible to turn of the routeplanner and the info window at the upper left corner?

**Comment by edwerf** [comment]
Before I used Reumer maps in which I was able to show my own created map by the mid code. Is this possible with this plugin as well? The line below doesn't work.

{google_map}mid=1tOIX7F_S9Brp6vvEn9UjH2YYUeE|18.78432,18.78432|zoom:30|{/google_map}

**Comment by petkivim** [comment]
Unfortunately it's not possible to disable the route planner and the info window.

It's possible to show a map that you have created by yourself. You just need to use the full URL of the map, e.g.

```
{google_map}https://maps.google.com/maps/ms?msid=217161423031772948547.000466f9688324d5a1b35&msa=0{/google_map}
```

**Comment by edwerf** [comment]
Dear Petteri,

Thank you very much for your quick reply.

Your example works. But when I replace your link in my map it doesn't work with {google_map}https://www.google.com/maps/d/edit?hl=en&authuser=0&mid=1tOIX7F_S9Brp6vvEn9UjH2YYUeE&ll=19.329781954014635%2C99.34029785000007&z=9{/google_map}

I did try to use your link with my msid code, but unfortunately no result as well. Could you please inform me about my mistake? I would like to zoom on 1 location in the map.

My map is https://www.google.com/maps/d/edit?hl=en&authuser=0&mid=1tOIX7F_S9Brp6vvEn9UjH2YYUeE&ll=19.329781954014635%2C99.34029785000007&z=9. The article on my website is http://khemtittravel.nl/index.php/inside-information/chiang-mai/restaurants-in-chiang-mai/740-sila-aat-restaurant-chiang-mai#info

Thank you for your help.

With best regards,
Edwin


On Wed, Nov 2, 2016 at 1:55 AM, Petteri Kivimäki <notifications@github.com> wrote:

Unfortunately it's not possible to disable the route planner and the info window.

It's possible to show a map that you have created by yourself. You just need to use the full URL of the map, e.g.

{google_map}https://maps.google.com/maps/ms?msid=217161423031772948547.000466f9688324d5a1b35&msa=0{/google_map}

**Comment by petkivim** [comment]
Hi Edwin,

Thank you for the additional information. I tested the code below and it should do the trick. The correct URL can be found under Settings -> Embed Map. The map is centered automatically by Google Maps so unfortunately it's not possible to zoom on single location on the map.

```
{google_map}https://www.google.com/maps/d/embed?mid=1tOIX7F_S9Brp6vvEn9UjH2YYUeE{/google_map}
```

Br,
Petteri

**Comment by edwerf** [comment]
Dear Petteri,

Thank you very much for your information.

It's a pity that it's not possible to zoom on a single location. Till now I use the plugin of Mike Reumer Maps where this is possible. See my map http://khemtittravel.nl/index.php/inside-information/chiang-mai/restaurants-in-chiang-mai/720-riverside-restaurant#adres.

I am looking for an alternative for Reumer Maps which can me a commercial plugin as well. It looks like Mike Reumer doesn't support his Reumer Maps plugin anymore. Before support was great. Now he doesn't answer on multiple e-mail.

With best regards,
Edwin



On Wed, Nov 2, 2016 at 11:51 PM, Petteri Kivimäki <notifications@github.com> wrote:

Hi Edwin,

Thank you for the additional information. I tested the code below and it should do the trick. The correct URL can be found under Settings -> Embed Map. The map is centered automatically by Google Maps so unfortunately it's not possible to zoom on single location on the map.

{google_map}https://www.google.com/maps/d/embed?mid=1tOIX7F_S9Brp6vvEn9UjH2YYUeE{/google_map}


Br,
Petteri

**Comment by petkivim** [comment]
Hi Edwin,

It seems that the plugin that you're currently using is based on Google Maps JavaScript API that supports zooming on a single location and many other more advanced features. My plugin is based on the embed feature of the regular Google Maps and Google Maps Embed API that are both more simple and lack many features that are included in the JavaScript API. Supporting more advanced features would mean implementing support for the JavaScript API. This is something that can be considered in the future versions, but unfortunately it does not solve your problem here and now.

Br,
Petteri

**Comment by edwerf** [comment]
Dear Pettiri,

Thank you very much for your quick reply.

I am interested in your future versions and will follow your plugin. In the meanwhile I will find out if http://joomla.zhuk.cc/index.php/zhgooglemap-main is an alternative to fulfill my needs at this moment.

With best regards,
Edwin



On Sat, Nov 5, 2016 at 1:30 AM, Petteri Kivimäki <notifications@github.com> wrote:

Hi Edwin,

It seems that the plugin that you're currently using is based on Google Maps JavaScript API that supports zooming on a single location and many other more advanced features. My plugin is based on the embed feature of the regular Google Maps and Google Maps Embed API that are both more simple and lack many features that are included in the JavaScript API. Supporting more advanced features would mean implementing support for the JavaScript API. This is something that can be considered in the future versions, but unfortunately it does not solve your problem here and now.

Br,
Petteri
