### ISSUE TITLE
Embed Google Maps plugin suddenly not working

### ISSUE THREAD

**Issue by Grice2011** [petkivim/embed-google-map#38]
I have had this Joomla plugin working fine on my website for the past year. Just recently it has stopping working; the space for the map appears but no map. If you go to this webpage: https://sketchuptraining.com.au/sketchuptraining/courses/sketchup-modelling-essentials.html and click on one of the cities at the bottom of the page, the drop down form should show the venue on google maps; instead it shows a blank space in its place. Happens on both Firefox and Safari but not sure about other browsers. It could be a recent Joomla update causing it.

**Comment by petkivim** [comment]
Thanks for contacting me. It's nice to hear that you're using my Embed Google Maps plugin. I noticed that you're not using HTTPS for embedding the maps and I think that switching to HTTPS could solve the problem. Just login to admin site, go to Embed Google Map plugin settings and switch the ```HTTPS``` setting to ```Yes```. Let me know if that helps.

Br,
Petteri

**Comment by Grice2011** [comment]
Gee, I looked through the settings but did not see this option but did not see this option at the time. Thank you!

**Comment by petkivim** [comment]
You're welcome! :)
