### ISSUE TITLE
Module Custom HTML

### ISSUE THREAD

**Issue by sushismb** [petkivim/embed-google-map#39]
Hello,

I tried to use the code on the custom html module but it doesn't work. 

Is there anything I need to do to have it work?

Thank you!

**Comment by petkivim** [comment]
Hi,

Have you set the ```Prepare Content``` setting to ```Yes``` on the module's options?

Petteri

**Comment by sushismb** [comment]
Hello petkivim,

It solved the issue.

Thank you!

**Comment by petkivim** [comment]
You're welcome! :)

Petteri
