### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by standib** [petkivim/embed-google-map#4]
I just installed and published this plugin.  I inserted the following code into a custom html module:{google_map}2430 N 56th Ave,hart,MI 49436{/google_map}
All I see is the code, not the map.  Any ideas?
URL: http://surrealrealities.com/websites/openhearth_j3/

**Comment by petkivim** [comment]
Custom HTML module's "Prepare Content" option is set to "No" by default, so you must set it to "Yes". You can find "Prepare Content" setting on the Options tab of your module's settings. Changing the value should fix the problem.

**Comment by IrynaKorolenko** [comment]
Hi, could you please check what is wrong with mine 
http://irynakorolenko.com/en/lifestyle/travels
I can only see the link

**Comment by petkivim** [comment]
@IrynaKorolenko Please try with the below code. I tested it and it should work.

 ```
{google_map}https://www.google.com/maps/d/embed?mid=zfyUaeNxmOo0.kIUF0hP2chBc{/google_map}
```

**Comment by IrynaKorolenko** [comment]
Thank you! It works, I will only need to change the map size.

Appreciate your help,
Iryna.

**Comment by petkivim** [comment]
You're welcome. Good to hear that the problem was solved.

Best regards,
Petteri
