### ISSUE TITLE
Responsive map

### ISSUE THREAD

**Issue by fuzmic2** [petkivim/embed-google-map#40]
Hi guys

I have embedded a map that is sized with |width:850|height:550|   If i don't use the size it will default to probably about 300 px. I wanted a full width map hence the sizing.

With this "fixed" size when the browsing is done in smaller device such as a mobile phone, the map does not response to the new size ie the map gets cropped.

How can i make it response?

Forget to say THANK YOU to Petteri for a easy and good product.
From Mike

**Comment by fuzmic2** [comment]
Just tried |width:100%|, IT WORK.  Petteri this must be the way, correct me if i am wrong.  Just for sharing.

**Comment by petkivim** [comment]
Hi Mike,

Yes, this is the correct way if you want the map to be responsive.

Thanks,
Petteri
