### ISSUE TITLE
Disable mouse scrolling

### ISSUE THREAD

**Issue by SawadeeKC** [petkivim/embed-google-map#41]
Hi Petteri,

Nice Google Map plugin but is there a way to disable the map zoom when the mouse is on the map.
When I open a page with a map on a mobile device, once the map is displayed I cannot scroll the page anymore, the map will zoom instead.

**Comment by petkivim** [comment]
Hi,

There's a setting in the admin backend that let's you disable mouse scrolling . Login to the admin panel, go to Embed Google Map plugin settings and set ```Scrolling``` to ```No```. That should solve the problem.

- Petteri

**Comment by SawadeeKC** [comment]
Thanks a lot, it works like that!

Kiitos! ;)

**Comment by petkivim** [comment]
You're welcome. :)

Petteri
