### ISSUE TITLE
multiple addresses

### ISSUE THREAD

**Issue by ruudschouwenaar** [petkivim/embed-google-map#42]
Hi, 

Great plugin!

I'd like to show a map with two markers. Is there a way to let the plugin show multiple address on the map?

Cheers,
Ruud

**Comment by petkivim** [comment]
Hi,

Thanks for contacting me. It's nice to hear that you're using my Embed Google Maps plugin.

If you want to embed a map with multiple locations, first you need to create a map in Google Maps and store it under My places.

After creating the map you can embed it in Joomla using my plugin. You should copy the URL from the Embed map screen of Google Maps. Please see the link below.

https://support.google.com/maps/answer/3544418?hl=en

You need to copy the URL from iframe src and place it inside {google_map} tags in Joomla. 

{google_map}https://maps.google.com/maps/....{/google_map}

Thanks,
Petteri
