### ISSUE TITLE
Can't get the Lat , Lon parameters to work.

### ISSUE THREAD

**Issue by aratkinson** [petkivim/embed-google-map#43]
{google_map}47.588824, 3.116796|width:650|height:500|border:1|border_style:solid|border_color:#000000{/google_map}

using the above line of code but the world map is displayed. If I click on view larger map on the top left side you can that the Lat , Lon have been seen by maps as 47.588824%2C+3.116796

Can somebody point in the right direction to fix this . many thanks 
Adrian

**Comment by petkivim** [comment]
Could you post the link to your site where you're using the plugin? If you have copied a part of the  code for embedding the map from a website it's possible that it contains HTML markup that's causing the problem. If I can see the HTML code that the plugin generates I can probably tell you what's causing the problem.

Thanks,
Petteri
