### ISSUE TITLE
Issue with JCE editor. Map replaces the editors iframe

### ISSUE THREAD

**Issue by sitte** [petkivim/embed-google-map#45]
If I enable plugin and add code 
`{google_map}Poland|width:100%|height:400px{/google_map}`
to the module in bottom of the page then map replaces JCE editors iframe. How map plugin detects in witch iframe it shuld be inserted?

**Comment by petkivim** [comment]
If you want to add a map to a module using my Embed Google Map plugin you should use Custom HTML plugin. In addition, you must set the ```Prepare Content``` setting to Yes on the module's options?

Regards,
Petteri

**Comment by sitte** [comment]
Yes, I added custom html module with this code:
{google_map}Poland|width:100%|height:400px{/google_map}
and it shows map on the bottom of the home page: https://legionhdk.conor.com.pl/
Problem is when on page is form with editor field (I cannot send link). Then the content of editor's iframe is replaced with map. I hink that plugins inserts googlemap iframe in to editos iframe (it may mistakes which iframe is his own). 
It looks like this then: 
https://legionhdk.conor.com.pl/images/temp/Edycja_profilu_-_2017-10-30_18.46.53.jpg

**Comment by petkivim** [comment]
Could you check the value of ```Load asynchronously``` setting from plugin settings? If the value is currently ```yes``` try to change the value to ```no```.

**Comment by sitte** [comment]
That fixed the problem. Thank you very much (It was Yes, I changed to No).
