### ISSUE TITLE
Maps in Contacts?

### ISSUE THREAD

**Issue by nickvarney** [petkivim/embed-google-map#46]
Hi,
Does the plugin work in Contacts? I am using a third party contact component called ALFContact. The contact page just shows the syntax. The same syntax produces a map in an Article so I'm guessing that there's an issue with Contacts, or a conflict with this Extension.
Many thanks,
Nick

**Comment by petkivim** [comment]
Hi Nick,

Thank you for your message. Unfortunately the plugin does not currently support Contacts. Articles and custom HTML modules are supported.

Regards,
Petteri
