### ISSUE TITLE
Include TITLE in the plugin

### ISSUE THREAD

**Issue by rytechsites** [petkivim/embed-google-map#49]
We are in the process of running very detailed Accessibility Checks, and we were hoping that your plugin would help us around the errors of:

1. Missing Title Attribute
2. Missing Lang Attribute

I know if we manually 'embed' the google map we can put in the 'title' attribute, but we can't figure out how to do this with the Lang.

We are using a google tool, WorldSpace, to test the accessibility of a page that we are loading your map to.

Any ideas how we can add the TITLE and LANG using this plugin?

FYI, I have a Google API key, so I'm using the 'embed option'...

**Comment by petkivim** [comment]
Sorry for the slow response. Please see below an example `iframe` generated by the plugin. Unfortunately the HTML code does not currently contain `title` and/or `lang` attributes. 

```
<iframe class="embedGoogleMap" style="border: 0px solid #000000" src="http://maps.google.com/?q=address&amp;z=12&amp;t=m&amp;output=svembed" width="900" height="900"></iframe>
```

Unfortunately, the attributes can not be added using the current version of the plugin. Adding them would require updating the plugin source code. 

Regards,
Petteri
