### ISSUE TITLE
Disable and enable scrolling

### ISSUE THREAD

**Issue by Guili82** [petkivim/embed-google-map#5]
Hi!
I'm using your plugin and it works great. But I was wondering if there is a way to disable scroll on the map when the mouse is out the map, but enable again when the mouse is in the map or you click on the map and, disable it again when the mouse leaves the map.

Hope you can help me with these.

Thanks!

**Comment by petkivim** [comment]
Hi,

Thank you for the feedback. It's nice to hear that you're using my Embed Google Maps plugin.

It's possible to disable scroll on the map. This can be implemented using CSS and jQuery. Please see a simple example below.

Wrap the ```{google_map}``` tags with a class (.maps in this example). Change the CSS of the ```iframe``` to ```pointer-events: none``` and then using jQuery's click function to the parent element you can change the iframe's CSS to ```pointer-events:auto```.

Embedding the map:

```
<div class='maps'>
    {google_map}address{/google_map}
</div>
```

CSS:

```
.maps iframe{
    pointer-events: none;
}
```

jQuery:

```
$('.maps').click(function () {
    $('.maps iframe').css("pointer-events", "auto");
});

$( ".maps" ).mouseleave(function() {
  $('.maps iframe').css("pointer-events", "none"); 
});
```

Best regards,
Petteri
