### ISSUE TITLE
Disable cookie set by Google

### ISSUE THREAD

**Issue by jjnxpct** [petkivim/embed-google-map#55]
Hi! It is possible to use Google Maps without setting a cookie (by Google) on the users device. In order to do this you need an API key and also use a different URL to embed the map:

https://maps.googleapis.com/maps/api/js?key=XXXXXXXX&callback=initMap

When you use this URL YouTube / Google will not set a cookie.

Would it be possible to add an option to your plugin to use this URL? Maybe a checkbox like 'use cookieless youtube API' or something like that. When setting this option the mentioned URL will be used.  You do need a API key for this...

It would save us a lot of time if you could implement this. Because else we need to replace the plugin with custom map code to prevent the cookie.

Thanks!

**Comment by jjnxpct** [comment]
I just realised this plugin uses 'embed' (iframe). I think I would prefer the js version of Google maps. And then uses the cookieless domein as mentioned in my first post. So I guess you could consider this a feature request. But I don;t know how actively this plugin is being developed. If not we will need to look for alternatives.

**Comment by petkivim** [comment]
Thank you for the feature request. You're right, the plugin uses `iframe`s and is not currently based on the js version of Google Maps. You're not the first one who's asking this feature, so it can be added to the backlog. However, I cannot promise when it'll actually be implemented.
