### ISSUE TITLE
Embed Google Map stop working under Joomla 3.8.8

### ISSUE THREAD

**Issue by goshillo** [petkivim/embed-google-map#56]
Hi,
Embed Google Map 2.1.0 stop working after update to joomla 3.8.8.
Can you please help?
Many thanks and regards

**Comment by petkivim** [comment]
Hi,

Have you checked the logs for error messages? What is shown in the UI - do you see `{google_map}address{/google_map}` tags, blank screen, error message etc.?

Regards,
Petteri

**Comment by goshillo** [comment]
I forgot to tell you that I made 2 modifications:
1) the Joomla update to 3.8.8
2) the https:// activation

On the UI only the button to get the full map is shown. No error
Which logs are you meaning?

The plugin script in the article is the following:
<p style="text-align: center;">{google_map}10052 rochemolles TO|width:900|height:900|version:classic|type:normal|zoom:12|show_info:yes{/google_map}</p>

The page where you can see the problem is the following:
https://www.chaletdellaguida.it/come-arrivare.html

Thanks for your help

**Comment by petkivim** [comment]
Ho dato un'occhiata al tuo sito e dovresti cambiare le impostazione del plugin. Devi andare su `Plugins: Content - Embed Google Map` e poi scegliere `HTTPS`=> `Yes`. Al momento il sito usa `HTTPS` e la mappa non si fa vedere perchè usa `HTTP` invece. Dovrebbe funzionare quando tutti e due usano `HTTPS`. Fammi sapere se è tutto a posto quando hai provato a cambiare le impostazione.

**Comment by vlasmar** [comment]
Hello

I have the same problem. My site is [barastravel.gr](https://barastravel.gr). I have set HTTPS to yes but no luck.

**Comment by goshillo** [comment]
vlasmar I need con cancel every cache, both joomla and browser, to get the plugin working after https change.

⁣Inviato da Blue ​

Il giorno 18 giu 2018, 12:22, alle ore 12:22, vlasmar <notifications@github.com> ha scritto:

**Comment by vlasmar** [comment]
I did that but it didn't fix.

**Comment by petkivim** [comment]
@vlasmar Could you post a link to your map so I could take a look at it?

**Comment by vlasmar** [comment]
the placemarker I want to show to the page is [here](https://www.google.gr/maps/place/39%C2%B038'11.4%22N+22%C2%B025'05.8%22E/@39.6364901,22.4160823,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d39.636486!4d22.418271)

**Comment by petkivim** [comment]
@vlasmar Could you post a link to your website where you want to embed the map?

**Comment by vlasmar** [comment]
[barastravel.gr](https://barastravel.gr/index.php/el/) is my website. and the embed map I want to show it at the bottom on every page.
![screenshot_1](https://user-images.githubusercontent.com/40355727/41667954-e8e82850-74b6-11e8-8a86-e8bba09f4062.png)

**Comment by petkivim** [comment]
@vlasmar I checked out your website and I don't see `{google_map}address{/google_map}` tags or HTML code generated by the plugin there at the moment. Have you checked Joomla's error logs?

The plugin supports Joomla article's and custom HTML module. Other modules are not supported. What's the type of the module where you trying embed the map?

**Comment by vlasmar** [comment]
At the error log I don't see something for this plugin.
It's a Custom HTML module.
Could you help me if I send you administrator passwords?

**Comment by petkivim** [comment]
Yes, I can take a look at your site if you send me the credentials. Please use my email address dinky_jackson (a) hotmail.com
