### ISSUE TITLE
Resizing map from webpage to mobile

### ISSUE THREAD

**Issue by 123honeytree** [petkivim/embed-google-map#57]
Hi, I was trying to have the map resize according to the screen size of the device.
I put in "25%" as the height and "60%" as the width. The width resizes nicely according to the device, but the height stays at about 188px, regardless I change the height to "50%" or "auto", it still stays at 188px. It would only change its height if I put in the exact number of px. Please help, thanks!

**Comment by petkivim** [comment]
Hi,

The height is relative to the parent element of the map so it's most likely the parent element that does not allow the height of the map to scale. Try to adjust the height of the parent element and see if that helps.

Regards,
Petteri
