### ISSUE TITLE
Parameters not  working

### ISSUE THREAD

**Issue by petitpoisson** [petkivim/embed-google-map#60]
Example on this page : 
https://www.petitpoisson.be/contact 

Code is this : 
{google_map}Petitpoisson|version:classic|show_info:no|50.5992625,5.4918702|width:100%|height:400px|zoom:11{/google_map} 

Two issues : 

1. version (classic, embed, new) dont't work : I always have classic. Same with "show_info" : it's always shown, parameter doesn't change anything. 

2. On mobile (Chrome iOS), map is not centered on marker… 

Can you help? Thanks :-)

**Comment by petitpoisson** [comment]
Thanks, but not quite. Using either version, zoom, width and height work. embed and show_info don't…

**Comment by petkivim** [comment]
Unfortunately, `version` and `show_info` parameters are not supported by Google Maps anymore. Earlier Google Maps supported them, but now they seem to be ignored.
