### ISSUE TITLE
Conflict between Google Recaptcha and Map

### ISSUE THREAD

**Issue by meacwd** [petkivim/embed-google-map#62]
Hi i'm having an issue having maps and a google recaptcha box on a form on the same page, the recaptcha  shows and then disappears then the map shows where the recaptcha should be, wondering if you've come ac ross this before and if there's a work around.

Thanks

**Comment by leetempest** [comment]
I have exactly the same issue and can no longer use the plugin on contact pages. Usually I put the {google_map} code in the Miscellaneous text box of the Contact. But as mentioned this then renders the map in the Captcha location also.

**Comment by petkivim** [comment]
Hi,

I tried to replicate your problem using `CAPTCHA - reCAPTCHA` plugin. I added the reCAPTCHA box on the contact page in the Contact Form section, and a Google Map using `{google_map}` code on the same page in the Miscellaneous Information section. Both reCAPTCHA and Google Map were rendered successfully without problems. Unfortunately, I'm not able to replicate your problem.

I used Joomla v3.9.2, reCAPTCHA v2 and Embed Google Map v2.1.0.

Regards,
Petteri

**Comment by meacwd** [comment]
Hi Pettri

I'm using the rsforms component with the reCAPTCHA v2 plugin and Embed Google Map v2.1.0 with Joomla 3.9.1 at the moment and the problem is defintely there (I have also contacted rsforms but they suggested i spoke to you.), i've attached a screenshot showing the problem, i'm happy to show the site in question if we can arrange a time for me to enable the map again unfortunately i just can't leave the map enabled all the time as customers can't use the contact form.

Thanks

Gavin

![recaptcha_problem](https://user-images.githubusercontent.com/46445481/51474393-03963480-1d77-11e9-8548-1b3ea8ad08e2.jpg)

**Comment by petkivim** [comment]
Hi Gavin,

Are you using the free version of RSForm! or RSForm!Pro? And about the reCAPTCHA v2 plugin that you're using, is it RSForm!Pro - ReCAPTCHA? Unfortunately, I'm not able to test my plugin with the pro version, because it requires buying a license.

Regards,
Petteri

**Comment by meacwd** [comment]
Hi Petteri

Yes i am using the pro version i have a developer licence so if your able to give me a test domain i can send you an update code to get the pro version for testing along with the recaptcha plugin download.

Thanks

Gavin

**Comment by hjelperne** [comment]
Hi,

I can verify that the same issue happens with Chronoforms (FREE - currently version - 6.0.23)
with the Google Recaptcha v2 added to the form - but only with 2 maps in same page - AND the "Load map async" setting to "Yes". (So I turned off async for now..)

Hope it might help,

Best regards,
M

**Comment by petkivim** [comment]
Hi,

@hjelperne, thank you for the additional information. It helped me to resolve the problem. Version 2.1.2 provides a fix to the problem.

@leetempest, @meacwd Please update the plugin to version 2.1.2 and let me know if the problem is resolved.

https://github.com/petkivim/embed-google-map/raw/master/archive/plg_content_embed_google_map-2.1.2.zip

Thanks,
Petteri

**Comment by meacwd** [comment]
Hi Petteri

Thanks for the update it looks like thats resolved the problem for me.

Gavin
