### ISSUE TITLE
Erro showing on pages now that I am using PHP 7.1

### ISSUE THREAD

**Issue by PaulMlynarz** [petkivim/embed-google-map#63]
Using PHP 7.1 and Joomla 3.92 - Using Embed Google Maps 2.1 (just re-downloaded/re-installed)

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgContentembed_google_map has a deprecated constructor in /home/wphmotel/public_html/plugins/content/embed_google_map/embed_google_map.php on line 21

Any ideas?

Thanks

**Comment by petkivim** [comment]
Hi,

It might be the same problem described in this issue:

https://github.com/petkivim/embed-google-map/issues/47

You could try the same fix - change line 19 in the `embed_google_map.php` file from:

` function __construct(&$subject, $params) {`

to

` function __construct(& $subject, $params) {`

For some reason in some environments the plugin doesn't work without the space, and in other environments it works just fine even if PHP7 is used in both cases.

Regards,
Petteri

**Comment by petkivim** [comment]
Hi,

The fix described in my previous comment is included in the version [2.1.1](https://github.com/petkivim/embed-google-map/releases/tag/v2.1.1).

Regards,
Petteri
