### ISSUE TITLE
zoom functiuon not working

### ISSUE THREAD

**Issue by SawadeeKC** [petkivim/embed-google-map#66]
Hi,

I would like to zoom on a map but it doesn't work. I've tried different values but the map is all the time displayed on the same scale.

{google_map}https://www.google.com/maps/d/u/1/embed?mid=1AaU9l-PvxEc7XzIXSRZBBOSWgWfh5ewi|type:satellite|zoom:10|version:embed|show_info:yes|border:1|https:yes|link:yes|link_label:Open the map on another tab{/google_map}

**Comment by petkivim** [comment]
Hi,

I added the map to my test site and zoom works there as expected.

<img width="408" alt="map" src="https://user-images.githubusercontent.com/575897/53177861-748c6e80-35f9-11e9-965b-948427213c80.png">

You could try to copy/paste the code below to your website and see if it works after that. Currently there might be some HTML formatting included in the code that's causing the problem.

```
{google_map}https://www.google.com/maps/d/u/1/embed?mid=1AaU9l-PvxEc7XzIXSRZBBOSWgWfh5ewi|type:satellite|zoom:10|version:embed|show_info:yes|border:1|https:yes|link:yes|link_label:Open the map on another tab{/google_map}
```

Regards,
Petteri

**Comment by SawadeeKC** [comment]
Hi Petteri,

Thank you for your answer.
I copied and paste your code and it doesn’t change anything, the map is still very small. I tried with Safari, Chrome and Firefox but it’s the same on all explorers.

Here is the page where I’ve added the code:
https://www.sawadeekohchang.com/where-to-stay/awarded-resorts <https://www.sawadeekohchang.com/where-to-stay/awarded-resorts>

Regards,

David

**Comment by petkivim** [comment]
Hi David,

I'm sorry, I didn't understand what you wanted to do until now. Change the `version` parameter from `embed` to `classic` ( `version:classic`) and that should do the job.

```
{google_map}https://www.google.com/maps/d/u/1/embed?mid=1AaU9l-PvxEc7XzIXSRZBBOSWgWfh5ewi|type:satellite|zoom:11|version:classic|show_info:yes|border:1|https:yes|link:yes|link_label:Open the map on another tab{/google_map}
```

Regards,
Petteri

**Comment by SawadeeKC** [comment]
Thanks a lot for your help!
