### ISSUE TITLE
Embed google map in module position

### ISSUE THREAD

**Issue by katuxa** [petkivim/embed-google-map#68]
Hi
Am using your plugin on a few sites and its great and one of the few plugins that isn't giving the error 'for development purposes only'.
However am trying to place it in a module position and it only shows the 'tags' not the map.
I tries using a custom html module and then tries using 'article anywhere ' plugin but it only shows the {google_map} tags

Any way around this?
Thanks

**Comment by petkivim** [comment]
Hi,

Embed Google Map can be used inside a Custom HTML module. By default, the Prepare Content setting of a new Custom HTML module is set to `No` on the module's options. You should change the Prepare Content setting's value to `Yes`and after that the plugin should work.

Best regards,
Petteri

**Comment by barnstormp** [comment]
Hello - Enjoying your plugin working quite well for me in articles. Is is possible to take multiple locations ie address in one map?
Thanks!

**Comment by petkivim** [comment]
Hi @barnstormp 

If you want to embed a map with multiple locations, first you need to create a map in Google Maps and store it under My places.

After creating the map you can embed it in Joomla using my plugin. You should copy the URL from the Embed map screen of Google Maps. Please see the link below.

https://support.google.com/maps/answer/3544418?hl=en

You need to copy the URL from iframe src and place it inside {google_map} tags in Joomla.

```
{google_map}https://maps.google.com/maps/....{/google_map}
```

Regards,
Petteri

**Comment by barnstormp** [comment]
Thank you!
