### ISSUE TITLE
Resize map dynamically?

### ISSUE THREAD

**Issue by vanislman** [petkivim/embed-google-map#7]
Hi,
Great plugin. It's simple, looks good and I love the functionality. Thanks a lot for developing this !

I'm using it on various websites which I just converted to be fully responsive. Is it possible to use this plugin in a way that the size of the map dynamically changes base on the device size?

Thanks
Hermann

**Comment by petkivim** [comment]
Hi,

Thank you for the feedback. It's nice to hear that you're using my Embed Google Map plugin.

It should be possible to make the map responsive using CSS. The map is inside ```iframe``` element which is responsive. You can place the map inside a wrapper element and give it an ID which makes it easier to adjust the iframe holding the map if there are other iframes on the same page.

Best regards,
Petteri

**Comment by petkivim** [comment]
Hi,

The easiest way to make the map scalable is to use percent when defining width and height of the map. For example:

```
{google_map}address|width:80%|heigth:60%{/google_map}
```

Best regards,
Petteri
