### ISSUE TITLE
<frame> or <iframe> elements do not have a title

### ISSUE THREAD

**Issue by Cpointcc** [petkivim/embed-google-map#70]
In my goal to achieve ADA compliance, I have been flagged on my auditor for my google maps.

Is it possible for you to add this to the code or do I need to do a custom overwrite?  If so what file needs to be modified?

Please advise.

**Comment by petkivim** [comment]
Yes, I can add a `title` attribute to the `iframe` element. Is it OK to have a fixed title, e.g. "A map by Google Maps", or do you need to be able specify the title for each map separately?

Regards,
Petteri

**Comment by Cpointcc** [comment]
The generic is fine if that is the only option.  Of course for SEO, if possible the map name would be ideal.

Sincerely,
[sue-grady-signature-email]

Sue Grady
IT Specialist/Web Developer
1622 4th Street
Peru, IL  61354
P:  815-223-1052
F:  815-223-0791
E:  sgrady@cpointcc.com<mailto:sgrady@cpointcc.com>

**Comment by petkivim** [comment]
Hi,

The version 2.3.0 adds the `title` attribute by default. It's possible to override the default title using the `title` parameter:

```
{google_map}address|title:iframe title attribute{/google_map}
```

https://github.com/petkivim/embed-google-map/releases/tag/v2.3.0

Best regards,
Petteri

**Comment by Cpointcc** [comment]
Good day, I will give that a try and see if that resolves the issue.

Thank you!


[sue-grady-signature-email]

Sue Grady
IT Specialist/Web Developer
1622 4th Street
Peru, IL  61354
P:  815-223-1052
F:  815-223-0791
E:  sgrady@cpointcc.com<mailto:sgrady@cpointcc.com>

**Comment by Cpointcc** [comment]
Hello Petteri,

I have added the the code per your suggestion.  Maybe I don't have the correct syntax.  I am still getting the error.

Here is the code I have tried unsuccessfully:

{google_map}1622 4th Street, Peru, IL  61354 | title: Map to Connecting Point{/google_map}

{google_map}1622 4th Street, Peru, IL  61354 | Map to Connecting Point{/google_map}

Please advise.

Thanks so much!

**Comment by petkivim** [comment]
Hi Sue,

You're welcome. Nice to hear that the problem is now resolved.

Best regards,
Petteri
