### ISSUE TITLE
responsive features?

### ISSUE THREAD

**Issue by gnostic19** [petkivim/embed-google-map#71]
hello,

unless i set the plug-in to 350px or less i am unable to see a map displayed on a phone. Is there a way to set a responsive code when placing the html for the map in a custom module? The map looks out of sorts when it's 350x250 on a desktop.

thanks

**Comment by petkivim** [comment]
Hi,

Have you tried to set to set height and width using `%` instead of `px`? In that case height and width are relative to the parent element of the map and the map scales within the boundaries set by the parent.

Regards,
Petteri
