### ISSUE TITLE
How to change colorscheme

### ISSUE THREAD

**Issue by cappuccinonet** [petkivim/embed-google-map#72]
Dear Petteri Kivimäki,
is it possible to change the color scheme like here https://mapstyle.withgoogle.com/ - and if so, how to implement in your plugin.
Thanks and kind regards,
Bernhard

**Comment by petkivim** [comment]
Hi @cappuccinonet 

The styling tool is for Google Maps that are using the static Google Maps API. Unfortunately, my plugin is not using the API and therefore, the tool cannot be used to customize the layout of the maps generated by my plugin.

Best regards,
Petteri
