### ISSUE TITLE
Embed a Google Map into a Joomla Page doesnt work anymore

### ISSUE THREAD

**Issue by johnniek2** [petkivim/embed-google-map#76]
Embed a Google Map into a Joomla Page doesnt work anymore? is there a workaround or is it related to the API?
I havent used an API before

**Comment by Lazaaa** [comment]
Refused to display 'http://maps.google.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by johnniek2** [comment]
dont understand what you are saying? is there a fix? how can I make it work again?

**Comment by petkivim** [comment]
Could you share a link to your website so that I could try to debug the problem? Alternatively, please provide a more detailed description of the problem.

**Comment by johnniek2** [comment]
> 
> 
> Could you share a link to your website so that I could try to debug the problem? Alternatively, please provide a more detailed description of the problem.

Hi Thank you it was our website: [https://www.zadarbike.com/contact-us-book-a-bike/our-location-in-zadar-city.html](url) and the problem persisted for several day.... now when I went to check its working? can you still check if there is something in conflict maybe' in the code? Thank you

**Comment by petkivim** [comment]
Thanks for sharing the link! I checked out the site and the map seems to be working now. Also, the code is OK and I didn't find any problems with it. Probably it was a temporary hiccup on Google's side.

**Comment by johnniek2** [comment]
thx a lot
