### ISSUE TITLE
Plugin shows only code in frontend

### ISSUE THREAD

**Issue by MrKingCobra** [petkivim/embed-google-map#77]
Hello,
I use your plugin already with success for years, but on my latest test website for a new project it fails and I don't kno why.:
https://www.mijnsbergen.online/golf/
I think I have done the same as in my other websites but now it shows only the code in the frontend.
I used the exact code in the current version of the golfclub's website
https://www.golfclubmolenberg.nl/
And there it shows the map!
Can you help me out please?
Best regards,
Chris Mijnsbergen

![screenshot-googlemaps](https://user-images.githubusercontent.com/96005653/145710959-0e9e89a9-5010-4c74-9a60-67168d0bf2a0.png)

**Comment by petkivim** [comment]
Hi,

Thank you for your message. First, could you check the following configuration items:

1. The plugin is enabled: 
   - Extensions -> Plugins -> Embed Google Map -> Status -> Enabled
2. Prepare content is set to `Yes` if you're using a custom HTML module: 
   - Extensions -> Modules -> Your Module -> Options -> Prepare Content -> Yes

Br,
Petteri

**Comment by MrKingCobra** [comment]
Thanks for quick response and solution.
It was no. 2 I forgot to do!
It was already some time ago I put in an Google map with you plugin.
Best regards,
Chris
