### ISSUE TITLE
Passing PHP parameter to map plugin

### ISSUE THREAD

**Issue by dievel** [petkivim/embed-google-map#8]
Hi,
I'm getting an address, city and other information about a place from a DB. I need to visualize this place in the google map plugin. I stored these information in PHP variables. I wrote the following line:

{google_map}<?php $address . ' ' . $city ?>|width:100%|height:300|zoom:10|lang:it{/google_map}

In this way, I can see the map as a result, but it is not centered on my point and my point has no marker in the map. Basically, it is a default map.
How can I get the desider result?
Thanks in advance,
Moreno

**Comment by petkivim** [comment]
Hi,

Are using the below line in a template or in an article?

```
{google_map}<?php $address . ' ' . $city ?>|width:100%|height:300|zoom:10|lang:it{/google_map}
```
If you're using it in a template, it should be enough to add ```echo``` and a semicolon.

```
{google_map}<?php echo $address . ' ' . $city; ?>|width:100%|height:300|zoom:10|lang:it{/google_map}
```

If you'd like to use PHP in articles, it can be done in several [ways](http://www.walkswithme.net/how-to-include-html-or-php-codes-into-joomla-article).

Best regards,
Petteri

**Comment by dievel** [comment]
I'm sorry,
you are perfectly right, I was missing the echo...

Thanks a lot and congratulation for the good plugin.
Moreno

**Comment by petkivim** [comment]
Thanks. Good to hear that the problem was solved. :)

Best regards,
Petteri
