### ISSUE TITLE
toggle off POI

### ISSUE THREAD

**Issue by grantiago** [petkivim/embed-google-map#82]
Another request not an issue. An option to toggle off POIs. 

`var style = [
        {
            featureType: \"poi\",
            elementType: \"business\",
            stylers: [{ visibility: \"off\" }]
			/*stylers: [{ visibility: {$this->poi} }]*/`

**Comment by petkivim** [comment]
Unfortunately, also this feature would require using the Google Maps JavaScript API. Since the plugin is based on the embed feature of the regular Google Maps and Google Maps Embed API , toggling off POIs can't be supported.

**Comment by grantiago** [comment]
Thanks for the response. I wondered why you had the map in an iframe. Nice plugin.
