### ISSUE TITLE
Embed code not working in module

### ISSUE THREAD

**Issue by staffiery** [petkivim/embed-google-map#83]
I was able to get the {google_map}{/google_map} code working in an Article and a K2 item, but when I place in a module the plugin appears to not be processed
![google_map-screenshot](https://user-images.githubusercontent.com/5347965/165363446-4dc89d5d-d3bc-439f-8a07-ca5801d62016.png)

Is it possible to use your plugin with other extensions and/or modules?

**Comment by petkivim** [comment]
Hi,

Embed Google Map can be used inside a Custom HTML module. By default, the Prepare Content setting of a new Custom HTML module is set to No on the module's options. You should change the Prepare Content setting's value to `Yes` and after that the plugin should work:

- Extensions -> Modules -> Your Module -> Options -> Prepare Content -> Yes

Best regards,
Petteri

**Comment by staffiery** [comment]
Thanks for the quick reply. I’ll give this a try as soon as I get in today.

**Comment by staffiery** [comment]
Thanks! That worked!!!!

 

Scott Staffiery
President & CEO
Interwave Travel Concepts, Inc.
6502 Breckenridge Way
Reno, NV 89523
Office: 775-787-0675
Mobile: 408-482-3771
***@***.*** ***@***.***> 
https://www.waveconcepts.com <https://www.waveconcepts.com/> 

 

 



CONFIDENTIALITY NOTICE: This e-mail message including attachments, if any, is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact Interwave Travel Concepts, Inc. by this e-mail and destroy all copies of the original message. If you are the intended recipient but do not wish to receive communications through this medium, please advise Interwave Travel Concepts, Inc. immediately. Thank you.

**Comment by petkivim** [comment]
Hi Scott,

You're welcome. I'm glad to hear that the problem was resolved.

Regards,
Petteri
