### ISSUE TITLE
Google Map not viewable on mobile

### ISSUE THREAD

**Issue by mpiliego** [petkivim/embed-google-map#84]
Hi, 
I've installed your plugin "Embed Google Map for Joomla" on website and it run perfectly.
But, when I try to navigate the site on android smartphone, the plugin is non viewble
What have I wrong? Can you help me to fix it?

You can see the issue navigating url "https://www.ilportoaffittacamere.it"

**Comment by petkivim** [comment]
Hi,

What browser and Android version are you using? And have you tried to view your site with different Android version / browser combinations? I tested your site with Android 11 and Chrome, and the map was visible and responsive. Therefore, I assume the problem has something to do with the Android version and/or browser.

**Comment by mpiliego** [comment]
Hi Petkiviim,
I'm using Google Chrome and Android 9... I've fixed the issue removing
google cookies from browser.
thankyou very much for support.

Mino Piliego

****** Riservatezza / Confidentiality ****
In ottemperanza al D.L. n. 196 del 30/6/2003 in materia di protezione dei
dati personali, le informazioni contenute in questo messaggio sono
strettamente riservate ed esclusivamente indirizzate al destinatario
indicato (oppure alla persona responsabile di rimetterlo al destinatario).
Vogliate tener presente che qualsiasi uso, riproduzione o divulgazione di
questo messaggio è vietato. Nel caso in cui aveste ricevuto questo
messaggio per errore, vogliate cortesemente avvertire il mittente e
distruggere il presente messaggio.



According to Italian law D.L. 196/2003 concerning privacy, if you are not
the addressee (or responsible for delivery of the message to such person)
you are hereby notified that any disclosure, reproduction, distribution or
other dissemination or use of this communication is strictly prohibited. If
you have received this message in error, please destroy it and notify us by
email.


Il giorno mer 27 apr 2022 alle ore 15:58 Petteri Kivimäki <
***@***.***> ha scritto:

**Comment by petkivim** [comment]
Hi Mino,

You're welcome. I'm glad to hear that the problem was resolved.

Regards,
Petteri
